apiVersion: apps.kubeblocks.io/v1alpha1
kind: BackupPolicyTemplate
metadata:
  name: mysql-backup-policy-template
  annotations:
    dataprotection.kubeblocks.io/is-default-policy-template: "true"
spec:
  backupPolicies:
    - componentDefs: [my-mysql]
      target:
        role: ""
        strategy: Any
        account: root
      backupMethods:
        - name: xtrabackup
          snapshotVolumes: false
          actionSetName: mysql-xtrabackup
          targetVolumes:
            volumeMounts:
              - name: data
                mountPath: /var/lib/mysql
        - name: volume-snapshot
          snapshotVolumes: true
          actionSetName: mysql-volumesnapshot
          targetVolumes:
            volumes:
              - data
            volumeMounts:
              - name: data
                mountPath: /var/lib/mysql
      schedules:
        - backupMethod: xtrabackup
          enabled: false
          cronExpression: "0 18 * * 0"
          retentionPeriod: 7d