apiVersion: apps.kubeblocks.io/v1beta1
kind: ConfigConstraint
metadata:
  name: mysql-config-constraints
spec:
  # configmap reference
  reloadAction:
    tplScriptTrigger:
      sync: true
      scriptConfigMapRef: mysql-reload-script


  # ConfigurationSchema that impose restrictions on engine parameter's rule
  parametersSchema:
    # top level mysql configuration type
    topLevelKey: MysqlParameter
    cue: |-
      #MysqlParameter: {
        // The size in bytes of the memory buffer innodb uses to cache data and indexes of its tables
        innodb_buffer_pool_size?: int & >=5242880 & <=18446744073709551615 @k8sResource(quantity)
        
        // The number of simultaneous client connections allowed.
        max_connections?: int & >=1 & <=100000
      
        // Each thread that does a sequential scan allocates this buffer. Increased value may help perf if performing many sequential scans.
        read_buffer_size: int & >=8200 & <=2147479552 | *262144
      
        // Avoids disk reads when reading rows in sorted order following a key-sort operation. Large values can improve ORDER BY perf.
        read_rnd_buffer_size: int & >=8200 & <=2147479552 | *524288
      
        // Increase the value of join_buffer_size to get a faster full join when adding indexes is not possible.
        join_buffer_size?: int & >=128 & <=18446744073709547520
      
        // Size of the buffer that is allocated when sorting MyISAM indexes during a REPAIR TABLE or when creating indexes with CREATE INDEX or ALTER TABLE.
        myisam_sort_buffer_size?: int & >=4 & <=9223372036854775807
      
        // Enables or disables the Performance Schema
        performance_schema: string & "0" | "1" | "OFF" | "ON" | *"0"
      
        gtid_mode?: string & "0" | "OFF" | "ON" | "1"
      
        // Prevents execution of statements that cannot be logged in a transactionally safe manner
        enforce_gtid_consistency?: string & "OFF" | "WARN" | "ON"
      
        // Maximum binlog cache size a transaction may use
        max_binlog_cache_size?: int & >=4096 & <=18446744073709547520
      
        // MySQL data directory
        datadir?: string
      }
  ## define static parameter list
  staticParameters:
    - performance_schema
    - enforce_gtid_consistency

  ## define dynamic parameter list
  dynamicParameters:
    - innodb_buffer_pool_size
    - max_connections
    - read_rnd_buffer_size
    - join_buffer_size
    - sort_buffer_size
    - gtid_mode

  ## define immutable parameter list, this feature is not currently supported.
  immutableParameters:
    - datadir



  # mysql configuration file format
  fileFormatConfig:
    format: ini
    iniConfig:
      sectionName: mysqld