apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |-
    [mysqld]
    {{- $phy_memory := getContainerMemory ( index $.podSpec.containers 0 ) }}
    {{- $phy_cpu := getContainerCPU ( index $.podSpec.containers 0 ) }}
    {{- $pool_buffer_size := ( callBufferSizeByResource ( index $.podSpec.containers 0 ) ) }}
    innodb_buffer_pool_size={{ $pool_buffer_size }}
    {{- $thread_stack := 262144 }}
    {{- $binlog_cache_size := 32768 }}
    {{- $join_buffer_size := 262144 }}
    {{- $sort_buffer_size := 262144 }}
    {{- $read_buffer_size := 262144 }}
    {{- $read_rnd_buffer_size := 524288 }}
    {{- $single_thread_memory := add $thread_stack $binlog_cache_size $join_buffer_size $sort_buffer_size $read_buffer_size $read_rnd_buffer_size }}
    max_connections={{ div ( div $phy_memory 4 ) $single_thread_memory }}
    read_buffer_size={{ $read_buffer_size }}
    read_rnd_buffer_size={{ $read_rnd_buffer_size }}
    join_buffer_size={{ $join_buffer_size }}
    sort_buffer_size={{ $sort_buffer_size }}
    
    {{- if lt $phy_memory 8589934592 }}
    performance_schema=OFF
    {{- end }}
    # gtid
    gtid_mode=ON
    enforce_gtid_consistency=ON
    # binlog
    binlog_cache_size={{ $binlog_cache_size }}
    # server
    {{- $data_root := getVolumePathByName ( index $.podSpec.containers 0 ) "data" }}
    datadir={{ $data_root }}/data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-reload-script
data:
  reload.tpl: |-
    {{- /* mysql global variable update */}}
    {{- /* mysql using system variables reference docs: https://dev.mysql.com/doc/refman/8.0/en/using-system-variables.html */}}
    {{- /*  1. system variable names must be written using underscores, not dashes. */}}
    {{- /*  2. string variable 'xxx' */}}
    {{- /*  3. type convert to number */}}
    {{- range $pk, $pv := $.arg0 }}
    {{- $pk = trimPrefix "loose_" $pk }}
    {{- $pk = replace "-" "_" $pk }}
    {{- $var_int := -1 }}
    {{- if $pv | regexMatch "^\\d+$" }}
    {{- $var_int = atoi $pv }}
    {{- end}}
    {{- if lt $var_int 0 }}
    {{- $tmp := $pv | regexStringSubmatch "^(\\d+)K$" }}
    {{- if $tmp }}
    {{- $var_int = last $tmp | atoi | mul 1024 }}
    {{- end }}
    {{- end }}
    {{- if lt $var_int 0 }}
    {{- $tmp := $pv | regexStringSubmatch "^(\\d+)M$" }}
    {{- if $tmp }}
    {{- $var_int =  last $tmp | atoi | mul 1024 1024 }}
    {{- end }}
    {{- end }}
    {{- if lt $var_int 0 }}
    {{- $tmp := $pv | regexStringSubmatch "^(\\d+)G$" }}
    {{- if $tmp }}
    {{- $var_int = last $tmp | atoi | mul 1024 1024 1024 }}
    {{- end }}
    {{- end }}
    {{- if ge $var_int 0 }}
    {{- execSql ( printf "SET GLOBAL %s = %d" $pk $var_int ) }}
    {{- else }}
    {{- execSql ( printf "SET GLOBAL %s = '%s'" $pk $pv ) }}
    {{- end }}
    {{- end }}
  reload.yaml: |-
    scripts: reload.tpl
    fileRegex: my.cnf
    formatterConfig:
      format: ini
      iniConfig:
        sectionName: mysqld
