apiVersion: dataprotection.kubeblocks.io/v1alpha1
kind: ActionSet
metadata:
  name: {{ include "mysql.componentDefName" . }}-xtrabackup
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  backupType: Full
  env:
    - name: DATA_DIR
      value: "{{ .Values.dataMountPath }}/data"
    - name: MYSQL_DIR
      value: {{ .Values.dataMountPath }}
    - name: IMAGE_TAG
      value: 8.0.32
    - name: BACKUP_FOR_STANDBY
      value: "false"
  backup:
    preBackup: []
    postBackup: []
    backupData:
      image: {{ .Values.image.xtraBackupRegistry | default "docker.io" }}/{{ .Values.image.xtraBackupRepository }}:8.0.33
      runOnTargetPodNode: true
      command:
        - bash
        - -c
        - |
        {{- .Files.Get "dataprotection/backup.sh" | nindent 10 }}
      syncProgress:
        enabled: true
        intervalSeconds: 5
  restore:
    prepareData:
      image: {{ .Values.image.xtraBackupRegistry | default "docker.io" }}/{{ .Values.image.xtraBackupRepository }}:8.0.33
      command:
        - bash
        - -c
        - |
        {{- .Files.Get "dataprotection/restore.sh" | nindent 10 }}
    postReady:
      - exec:
          command:
            - sh
            - -c
            - |
              rm -rf {{ .Values.dataMountPath }}/data/.restore_new_cluster