apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
metadata:
  name: {{ include "proxysql.componentDefName" . }}
  labels:
      {{- include "mysql.labels" . | nindent 4 }}
spec:
  provider: kubeblocks
  description: mysql proxy definition for Kubernetes
  serviceKind: proxysql
  serviceVersion: 2.4.4
  updateStrategy: BestEffortParallel

  configs:
    - name: proxy-config
      templateRef: my-proxysql-config
      namespace: {{ .Release.Namespace }}
      volumeName: proxy-config
      reRenderResourceTypes:
        - hscale
  scripts:
    - name: proxysql-scripts
      templateRef: my-proxysql-scripts
      namespace: {{ .Release.Namespace }}
      volumeName: proxysql-scripts
      defaultMode: 0555

  services:
    - name: proxy-server
      serviceName: proxy-server
      spec:
        ports:
          - name: db
            port: 6033
            targetPort: db
    - name: proxy-ordinal
      serviceName: proxy-ordinal
      podService: true
      spec:
        ports:
          - name: admin
            port: 6032
            targetPort: admin
          - name: db
            port: 6033
            targetPort: db

  lifecycleActions:
    accountProvision:
      customHandler:
        exec:
          image: {{ .Values.image.registry | default "docker.io" }}/apecloud/proxysql:2.4.4
          command:
            - mysql
            - -P${MYSQL_PORT}
            - -u${MYSQL_ROOT_USER}
            - -p${MYSQL_ROOT_PASSWORD}
            - -e "CREATE USER IF NOT EXISTS '${MYSQL_ROOT_USER}'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}'; GRANT ALL PRIVILEGES ON *.* TO ${MYSQL_ROOT_USER}"

  vars:
    - name: BACKEND_SERVER
      valueFrom:
        serviceVarRef:
          compDef: {{ include "mysql.componentDefName" . }}
          name: mysql
          host: Required
          optional: false

    - name: PROXYSQL_ENDPOINTS
      valueFrom:
        serviceVarRef:
          compDef: {{ include "proxysql.componentDefName" . }}
          name: proxy-ordinal
          host: Required
          optional: false

    - name: MYSQL_ROOT_USER
      valueFrom:
        credentialVarRef:
          ## reference the current component definition name
          compDef: {{ include "mysql.componentDefName" . }}
          name: root
          username: Required

    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        credentialVarRef:
          ## reference the current component definition name
          compDef: {{ include "mysql.componentDefName" . }}
          name: root
          password: Required

    - name: BACKEND_PORT
      valueFrom:
        serviceVarRef:
          compDef: {{ include "mysql.componentDefName" . }}
          name: mysql
          optional: false
          port:
            name: mysql
            option: Required

  runtime:
    containers:
      - name: proxysql
        image: {{ .Values.image.registry | default "docker.io" }}/apecloud/proxysql:2.4.4
        args:
          - /scripts/proxysql/proxysql-entry.sh
          - --reload
        volumeMounts:
          - mountPath: /etc/custom-config
            name: proxy-config
          - mountPath: /scripts/proxysql
            name: proxysql-scripts
        env:
          - name: LOAD_BALANCE_MODE
            value: GroupReplication
          - name: BACKEND_TLS_ENABLED
            value: "false"
          - name: FRONTEND_TLS_ENABLED
            value: "false"
        ports:
          - containerPort: 6033
            name: db
            protocol: TCP
          - containerPort: 6032
            name: admin
            protocol: TCP
          - containerPort: 6070
            name: metrics
            protocol: TCP