apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
metadata:
  name: my-mysql
  labels:
      {{- include "mysql.labels" . | nindent 4 }}
spec:
  serviceVersion: 8.0.33
  provider: kubeblocks
  description: mysql component definition for Kubernetes
  serviceKind: mysql

  updateStrategy: BestEffortParallel

  configs:
    - name: mysql-config
      volumeName: mysql-config
      templateRef: my-mysql-config
      constraintRef: my-mysql-config-constraints
      namespace: {{ .Release.Namespace }}
      reRenderResourceTypes:
        - vscale

  scripts:
    - name: mysql-scripts
      templateRef: my-mysql-scripts
      namespace: {{ .Release.Namespace }}
      volumeName: scripts
      defaultMode: 0555

  services:
    - name: mysql
      serviceName: mysql
      podService: true
      spec:
        ports:
          - name: mysql
            targetPort: mysql
            port: 3306

  systemAccounts:
    - name: root
      initAccount: true
      passwordGenerationPolicy:
        length: 10
        numDigits: 5
        numSymbols: 0
        letterCase: MixedCases

  vars:
    - name: MYSQL_ROOT_USER
      valueFrom:
        credentialVarRef:
          name: root
          username: Required

    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        credentialVarRef:
          name: root
          password: Required

  volumes:
    - name: data
      needSnapshot: true

  runtime:
    containers:
      - name: mysql
        image: mysql:8.0.33
        lifecycle:
          postStart:
            exec:
              command:
                - bash
                - -c
                - |
                  /scripts/init-mysql-instance.sh
        command:
          - bash
          - -c
          - |
            SERVICE_ID=$((${KB_POD_NAME##*-} + 1))
            docker-entrypoint.sh mysqld --server-id $SERVICE_ID

        ports:
          - name: mysql
            containerPort: 3306
        volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
          - name: mysql-config
            mountPath: /etc/mysql/conf.d
          - name: scripts
            mountPath: /scripts

        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - bash
              - -c
              - mysql -h 127.0.0.1 -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1