apiVersion: v1
kind: ConfigMap
metadata:
  name: my-mysql-config
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  my.cnf: |-
    {{- .Files.Get "config/mysql-config.tpl" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-mysql-reload-script
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  reload.tpl: |-
    {{- .Files.Get "config/mysql-reload.tpl" | nindent 4 }}
  reload.yaml: |-
    scripts: reload.tpl
    fileRegex: my.cnf
    formatterConfig:
      format: ini
      iniConfig:
        sectionName: mysqld