apiVersion: v1
kind: ConfigMap
metadata:
  name: my-mysql-scripts
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  init-mysql-instance.sh: |-
    {{- .Files.Get "scripts/init-mysql-instance.sh" | nindent 4 }}
  mysql-orchestrator-register.sh: |-
    {{- .Files.Get "scripts/mysql-orchestrator-register.sh" | nindent 4 }}
  cluster-info.sql: |-
    {{- .Files.Get "scripts/cluster-info.sql" | nindent 4 }}